export const SET_UI_GENERAL = "SET_UI_GENERAL"
export const SET_LANGUAGE = "SET_LANGUAGE"

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
export const GET_ALL_COURSE_OF_CATEGORY = 'GET_ALL_COURSE_OF_CATEGORY'

// export const SET_CURRENT_CATEGORY = ''


export const SET_SPECIFIC_COURSE = "GET_SPECIFIC_COURSE"




